---
- name: Enable proxy module
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - proxy
    - proxy_http
  notify:
      - Restart Apache

- name: Create .htpasswd-users
  template:
    dest: /etc/apache2/.htpasswd-users
    src: htpasswd-users.j2
    owner: "www-data"

- name: Create apache2 configuration
  template:
    src: vhost-configuration.j2
    dest: /etc/apache2/sites-available/jenkins-configuration.conf

- name: Check if jenkins vhost is enabled
  stat:
    path: /etc/apache2/sites-enabled/jenkins-configuration.conf
  register: jenkins_apache_vhost
  changed_when: false

- name: Enable apache2 vhosts
  shell: a2ensite jenkins-configuration.conf
  notify:
    - Restart Apache
  when: jenkins_apache_vhost.stat.exists == false
