---
- name: Create database user
  postgresql_user:
      name: "{{ item.owner }}"
      role_attr_flags: CREATEDB
  become: true
  become_user: postgres
  with_items: "{{ jenkins_db }}"
  tags: jenkins_db

- name: Create test database
  postgresql_db: 
      name: "{{ item.database }}"
      owner: "{{ item.owner }}"
  become: true
  become_user: postgres
  with_items: "{{ jenkins_db }}"
  tags: jenkins_db